apiVersion: v1
kind: Service
metadata:
  name: crm-api-svc
  namespace: digitrans
  labels:
    app: crm-api
spec:
  selector:
    app: crm-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
# NetworkPolicy – micro-segmentation : seul le namespace ingress peut atteindre le CRM
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: crm-api-netpol
  namespace: digitrans
spec:
  podSelector:
    matchLabels:
      app: crm-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432    # PostgreSQL
        - protocol: TCP
          port: 6380    # Redis SSL
        - protocol: TCP
          port: 443     # Azure services (Key Vault, Monitor)
        - protocol: UDP
          port: 53      # DNS
